module.exports = {

    NO_DATA_FOUND : {type: 'success', message: 'No Data Found.'},
    INCIDENT_ADDED_SUCCESSFULLY: {type: 'success', message: 'Incident Added Successfully.'},
    UNABLE_TO_ADD_INCIDENT: {type: 'error', message: 'Unable to Add Incident. Please Contact Admin.'},
    INCIDENT_UPDATED_SUCCESSFULLY: {type: 'success', message: 'Incident Updated Successfully.'},
    UNABLE_TO_UPDATE_INCIDENT: {type: 'error', message: 'Unable to Update Incident. Please Contact Admin.'},
    INCIDENT_DELETED_SUCCESSFULLY: {type: 'success', message: 'Incident Deleted Successfully.'},
    UNABLE_TO_DELETE_INCIDENT: {type: 'error', message: 'Unable to Delete Incident. Please Contact Admin.'},
    INCIDENT_BLOCKED_SUCCESSFULLY: {type: 'success', message: 'Incident has been Blocked/UnBlocked Successfully.'},
    UNABLE_TO_BLOCK_INCIDENT: {type: 'error', message: 'Unable to Block/UnBlock Incident. Please Contact Admin.'},
    INCIDENT_APPROVED_SUCCESSFULLY: {type: 'success', message: 'Incident has been Approved/ReferBack Successfully.'},
    UNABLE_TO_APPROVE_INCIDENT: {type: 'error', message: 'Unable to Approved/ReferBack Incident. Please Contact Admin.'},

    COOKBOOK_ADDED_SUCCESSFULLY: {type: 'success', message: 'Cook Book Added Successfully.'},
    UNABLE_TO_ADD_COOKBOOK: {type: 'error', message: 'Unable to Add Cook Book. Please Contact Admin.'},
    COOKBOOK_UPDATED_SUCCESSFULLY: {type: 'success', message: 'Cook Book Updated Successfully.'},
    UNABLE_TO_UPDATE_COOKBOOK: {type: 'error', message: 'Unable to Update Cook Book. Please Contact Admin.'},
    COOKBOOK_DELETED_SUCCESSFULLY: {type: 'success', message: 'Cook Book Deleted Successfully.'},
    UNABLE_TO_DELETE_COOKBOOK: {type: 'error', message: 'Unable to Delete Cook Book. Please Contact Admin.'},
    COOKBOOK_BLOCKED_SUCCESSFULLY: {type: 'success', message: 'Cook Book has been Blocked/UnBlocked Successfully.'},
    UNABLE_TO_BLOCK_COOKBOOK: {type: 'error', message: 'Unable to Block/UnBlock Cook Book. Please Contact Admin.'},
    COOKBOOK_APPROVED_SUCCESSFULLY: {type: 'success', message: 'Cook Book has been Approved/ReferBack Successfully.'},
    UNABLE_TO_APPROVE_COOKBOOK: {type: 'error', message: 'Unable to Approved/ReferBack Cook Book. Please Contact Admin.'},

    
    CUSTOMER_ADDED_SUCCESSFULLY: {type: 'success', message: 'Customer Added Successfully.'},
    UNABLE_TO_ADD_CUSTOMER: {type: 'error', message: 'Unable to Add Customer. Please Contact Admin.'},
    CUSTOMER_UPDATED_SUCCESSFULLY: {type: 'success', message: 'Customer Updated Successfully.'},
    UNABLE_TO_UPDATE_CUSTOMER: {type: 'error', message: 'Unable to Update Customer. Please Contact Admin.'},
    CUSTOMER_DELETED_SUCCESSFULLY: {type: 'success', message: 'Customer Deleted Successfully.'},
    UNABLE_TO_DELETE_CUSTOMER: {type: 'error', message: 'Unable to Delete Customer. Please Contact Admin.'},
    CUSTOMER_BLOCKED_SUCCESSFULLY: {type: 'success', message: 'Customer has been Blocked/UnBlocked Successfully.'},
    UNABLE_TO_BLOCK_CUSTOMER: {type: 'error', message: 'Unable to Block/UnBlock Customer. Please Contact Admin.'},
    CUSTOMER_APPROVED_SUCCESSFULLY: {type: 'success', message: 'Customer has been Approved/ReferBack Successfully.'},
    UNABLE_TO_APPROVE_CUSTOMER: {type: 'error', message: 'Unable to Approved/ReferBack Customer. Please Contact Admin.'},
}